# Generated by Django 6.0.6 on 2026-07-04 09:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_customer_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
