# Generated by Django 6.0.6 on 2026-07-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_driver_acknowledged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trip_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
