# Generated by Django 6.0.6 on 2026-07-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_remove_booking_driver_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_balance_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
