# Generated by Django 6.0.6 on 2026-07-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_last_balance_reminder_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_full_refund',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
