# Generated by Django 6.0.6 on 2026-07-09 18:43

import fleet.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[fleet.validators.validate_file_size]),
        ),
    ]
