# Generated by Django 6.0.6 on 2026-07-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_note_payment_recorded_by_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayout',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='needs_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
