# Generated by Django 6.0.6 on 2026-07-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_driver_suspension_reason'),
        ('payments', '0005_driverpayout_is_voided_driverpayout_voided_at_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverpayout',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='drivers.driver'),
        ),
    ]
