# Generated by Django 6.0.6 on 2026-07-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_add_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayout',
            name='b2c_conversation_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driverpayout',
            name='b2c_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
