# Generated by Django 6.0.7 on 2026-07-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_driverpayout_b2c_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='b2c_conversation_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='refund',
            name='b2c_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
