# Generated by Django 6.0.7 on 2026-07-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_refund_b2c_conversation_id_refund_b2c_failed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Referral Credit'), ('invoice', 'Government Invoice')], max_length=20),
        ),
    ]
