# Generated by Django 6.0.7 on 2026-07-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Referral Credit'), ('invoice', 'Invoice')], max_length=20),
        ),
    ]
