# Generated by Django 6.0.8 on 2026-08-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayout',
            name='aging_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
