"""
Django settings for silverlake project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path

from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-j4v=c0*78mzij*cq8*3abgz^z$b13bll(1@kxlu!tb(42&oqi1')

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (safe) - local development explicitly sets DEBUG=True in .env, so this only
# matters as a fallback for an environment that forgot to set it at all, e.g. a fresh production
# deploy - better that come up locked down than wide open.
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

if not DEBUG:
    # HTTPS enforcement - only in production, since local dev runs over plain http.
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year - browsers remember to always use https for this site
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Only needed if deployed behind a reverse proxy/load balancer that terminates TLS itself
    # and forwards plain http internally (Render, Railway, Heroku, an nginx front end, etc.) -
    # without this, SECURE_SSL_REDIRECT would redirect-loop forever since Django never sees the
    # request as secure. Leave this off (default) for a direct-to-Django HTTPS setup, e.g. a VPS
    # terminating TLS in Django/gunicorn itself.
    if config('BEHIND_HTTPS_PROXY', default=False, cast=bool):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',

    'accounts',
    'fleet',
    'drivers',
    'bookings',
    'payments',
    'reviews',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    # Vite picks the next free port (5174, 5175, ...) if 5173 is already taken, so allow any
    # localhost origin in dev rather than chasing the port number.
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='', cast=Csv())

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Rates for the specific public-facing views that set throttle_classes/throttle_scope
    # themselves (login, registration, password reset, the M-Pesa STK push triggers, and the
    # public driver application form) - everything else is unthrottled.
    'DEFAULT_THROTTLE_RATES': {
        'auth-login': '10/min',
        'auth-register': '5/hour',
        'auth-password-reset': '5/hour',
        'mpesa-stk': '5/min',
        'token-payment-view': '20/min',
        'driver-application': '5/hour',
    },
}

SIMPLE_JWT = {
    # Short-lived on purpose - the frontend's axios interceptor silently refreshes on a 401,
    # so there's no UX cost to keeping this tight. A short-lived access token also limits how
    # long a stolen one keeps working even after the refresh token behind it gets blacklisted
    # (see accounts.services.blacklist_all_tokens_for_user) - blacklisting only stops a refresh
    # token from minting new access tokens, it can't revoke an access token already issued.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
}

# Gmail SMTP for activation/password-reset emails.
# EMAIL_HOST_USER must be a full Gmail address; EMAIL_HOST_PASSWORD must be a 16-character
# Google "App Password" (requires 2FA enabled on that account) - NOT the normal account password.
# Generate one at https://myaccount.google.com/apppasswords
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'noreply@silverlakecarrentals.co.ke')

# Until real Gmail credentials are set, write emails to disk instead of crashing on send
# (the dev server runs in the background, so console output isn't visible to test against -
# check silverlake/sent_emails/ for the activation/reset link while testing).
if 'test' in sys.argv:
    # Never hit real SMTP (or write to disk) from the automated test suite.
    EMAIL_BACKEND = 'django.core.mail.backends.locmem.EmailBackend'
    # The full PBKDF2 iteration count is unnecessary (and slow) for tests that create lots
    # of throwaway users - this hasher is only used when 'test' is in sys.argv.
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']
    # Throttle state persists in the cache across test methods within the same run - without
    # this, tests that hit a throttled view more than a handful of times would start failing
    # on request count alone, not on what they're actually testing.
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        scope: '10000/min' for scope in REST_FRAMEWORK['DEFAULT_THROTTLE_RATES']
    }
elif EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
    EMAIL_FILE_PATH = BASE_DIR / 'sent_emails'

# Where the SPA lives, so emails can link back to activation/reset pages.
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')

ROOT_URLCONF = 'silverlake.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'silverlake.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploaded vehicle/driver photos)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
