# Generated by Django 6.0.7 on 2026-07-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clienterrorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienterrorreport',
            name='source',
            field=models.CharField(choices=[('client', 'Client'), ('scheduler', 'Background Job')], default='client', max_length=20),
        ),
    ]
