# Generated by Django 6.0.6 on 2026-07-03 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('license_number', models.CharField(max_length=50)),
                ('license_document', models.FileField(upload_to='driver_applications/licenses/')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_category', models.CharField(choices=[('executive_suv', 'Executive SUV'), ('premium_mpv', 'Premium MPV'), ('compact_sedan', 'Compact Sedan'), ('passenger_van', 'Passenger Van')], max_length=20)),
                ('passenger_capacity', models.PositiveSmallIntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='driver_applications/vehicles/')),
                ('vehicle_logbook_document', models.FileField(blank=True, help_text='Proof of vehicle ownership/registration', null=True, upload_to='driver_applications/logbooks/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drivers.driver')),
                ('created_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
