# Generated by Django 6.0.6 on 2026-07-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_finalize_vehicle_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cash_payments_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
