# Generated by Django 6.0.7 on 2026-07-24 08:28

import django.core.validators
import drivers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_alter_driver_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverapplication',
            name='license_document',
            field=models.FileField(help_text='Photo or PDF of your driving license, max 5MB', upload_to='driver_applications/licenses/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), drivers.validators.validate_file_size, drivers.validators.validate_document_content]),
        ),
        migrations.AlterField(
            model_name='driverapplication',
            name='vehicle_logbook_document',
            field=models.FileField(blank=True, help_text='Proof of vehicle ownership/registration, max 5MB', null=True, upload_to='driver_applications/logbooks/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), drivers.validators.validate_file_size, drivers.validators.validate_document_content]),
        ),
    ]
