# Generated by Django 6.0.8 on 2026-09-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0012_alter_driverapplication_license_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_expired_notified_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_expiry_warned_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
