# Generated by Django 6.0.6 on 2026-07-21 06:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_referralsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_completed_trips', models.PositiveIntegerField(help_text='Lifetime completed trips required to reach this tier.', unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Automatic discount applied to every booking once a customer reaches this tier.', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['min_completed_trips'],
            },
        ),
    ]
