# Generated by Django 6.0.6 on 2026-07-21 06:29

from django.db import migrations

# Sensible starting defaults so the loyalty program is actually live (not just wired) the moment
# this ships - an admin can freely retune or delete these afterward via the admin Loyalty Tiers
# page (core.views.AdminLoyaltyTierViewSet), same as ReferralSettings' own seeded default.
DEFAULT_TIERS = [
    ('Bronze', 0, 0),
    ('Silver', 3, 5),
    ('Gold', 6, 10),
    ('Platinum', 11, 15),
]


def seed_tiers(apps, schema_editor):
    LoyaltyTier = apps.get_model('accounts', 'LoyaltyTier')
    for name, min_trips, discount_percent in DEFAULT_TIERS:
        LoyaltyTier.objects.get_or_create(
            name=name, defaults={'min_completed_trips': min_trips, 'discount_percent': discount_percent},
        )


def unseed_tiers(apps, schema_editor):
    LoyaltyTier = apps.get_model('accounts', 'LoyaltyTier')
    LoyaltyTier.objects.filter(name__in=[name for name, _, _ in DEFAULT_TIERS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_loyaltytier'),
    ]

    operations = [
        migrations.RunPython(seed_tiers, unseed_tiers),
    ]
