# Generated by Django 6.0.7 on 2026-07-21 15:35

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_loginotp_twofactorsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[core.validators.validate_kenyan_phone_number]),
        ),
    ]
