# Generated by Django 6.0.8 on 2026-09-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='escalation_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
