# Generated by Django 6.0.6 on 2026-07-03 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Toyota Prado TZG', max_length=100)),
                ('category', models.CharField(choices=[('executive_suv', 'Executive SUV'), ('premium_mpv', 'Premium MPV'), ('compact_sedan', 'Compact Sedan'), ('passenger_van', 'Passenger Van')], max_length=20)),
                ('tagline', models.CharField(blank=True, help_text='e.g. Luxury - Power - Prestige', max_length=150)),
                ('passenger_capacity', models.PositiveSmallIntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fleet/')),
                ('is_available', models.BooleanField(default=True)),
                ('allow_self_drive', models.BooleanField(default=True)),
                ('allow_with_driver', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fleet/gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers show first')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
