# Generated by Django 6.0.6 on 2026-07-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_fleetpartner_vehicle_is_company_owned_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetpartner',
            name='mpesa_till_number',
            field=models.CharField(blank=True, help_text="Partner's own Till/Buy Goods number, if that's what they use instead of a Paybill", max_length=20),
        ),
        migrations.AlterField(
            model_name='fleetpartner',
            name='mpesa_consumer_key',
            field=models.CharField(blank=True, help_text='Daraja API key - fill in once the partner has one, not required to register', max_length=200),
        ),
        migrations.AlterField(
            model_name='fleetpartner',
            name='mpesa_consumer_secret',
            field=models.CharField(blank=True, help_text='Daraja API secret - fill in once the partner has one, not required to register', max_length=200),
        ),
        migrations.AlterField(
            model_name='fleetpartner',
            name='mpesa_passkey',
            field=models.CharField(blank=True, help_text='Daraja passkey - fill in once the partner has one, not required to register', max_length=200),
        ),
    ]
