# Generated by Django 6.0.6 on 2026-07-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_remove_fleetpartner_mpesa_consumer_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetpartner',
            name='payout_phone_number',
            field=models.CharField(blank=True, help_text="M-Pesa number this partner's own share of a payout is sent to - kept separate from contact_phone so a general contact number is never mistaken for a real money destination.", max_length=20),
        ),
    ]
