# Generated by Django 6.0.7 on 2026-07-21 15:35

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_favoritevehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetpartner',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[core.validators.validate_kenyan_phone_number]),
        ),
        migrations.AlterField(
            model_name='fleetpartner',
            name='payout_phone_number',
            field=models.CharField(blank=True, help_text="M-Pesa number this partner's own share of a payout is sent to - kept separate from contact_phone so a general contact number is never mistaken for a real money destination.", max_length=20, validators=[core.validators.validate_kenyan_phone_number]),
        ),
    ]
