# Generated by Django 6.0.7 on 2026-07-24 08:28

import django.core.validators
import fleet.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_alter_fleetpartner_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_document',
            field=models.FileField(blank=True, help_text='Insurance certificate, max 5MB', null=True, upload_to='fleet/insurance/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), fleet.validators.validate_file_size, fleet.validators.validate_document_content]),
        ),
        migrations.AlterField(
            model_name='vehiclesubmission',
            name='logbook_document',
            field=models.FileField(help_text='Proof of ownership/registration, max 5MB', upload_to='vehicle_submissions/logbooks/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), fleet.validators.validate_file_size, fleet.validators.validate_document_content]),
        ),
    ]
