# Generated by Django 6.0.8 on 2026-08-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0019_alter_vehicle_insurance_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='inspection_expired_notified_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inspection_expiry_warned_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expired_notified_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry_warned_for',
            field=models.DateField(blank=True, null=True),
        ),
    ]
