# Generated by Django 6.0.8 on 2026-09-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0020_vehicle_inspection_expired_notified_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='service_due_warned_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_overdue_notified_for',
            field=models.DateField(blank=True, null=True),
        ),
    ]
