# Generated by Django 6.0.6 on 2026-07-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_review_note_announcement_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Stops showing to its audience after this time. Leave blank to never expire on its own.', null=True),
        ),
    ]
