# Generated by Django 6.0.6 on 2026-07-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('travel_tips', 'Travel Tips'), ('destination_guides', 'Destination Guides'), ('fleet_spotlights', 'Fleet & Driver Spotlights'), ('company_news', 'Company News')], default='travel_tips', max_length=30),
        ),
    ]
