# Generated by Django 6.0.6 on 2026-07-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driverapplication_license_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, help_text='Used to notify the driver when they get booked', max_length=254),
        ),
    ]
