# Generated by Django 6.0.6 on 2026-07-04 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='away_reason',
            field=models.TextField(blank=True, help_text='Visible to admins only, not customers.'),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_away',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Login account for the driver portal, if one has been set up.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
