# Generated by Django 6.0.6 on 2026-07-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_driver_away_reason_driver_is_away_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
    ]
