# Generated by Django 6.0.8 on 2026-08-28 11:42

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_booking_review_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', validators=[reviews.validators.validate_file_size]),
        ),
    ]
