# Generated by Django 6.0.6 on 2026-07-04 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_driver_suspension_reason'),
        ('payments', '0002_driverpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_payments_recorded', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('cash', 'Cash')], max_length=10),
        ),
    ]
