# Generated by Django 6.0.6 on 2026-07-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_driverpayout_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayout',
            name='verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='dispute_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
    ]
