# Generated by Django 6.0.6 on 2026-07-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_cashdeposit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashDeposit',
        ),
    ]
