# Generated by Django 6.0.6 on 2026-07-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_delete_cashdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
