# Generated by Django 6.0.6 on 2026-07-10 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_finalize_vehicle_category_fk'),
        ('fleet', '0014_fleetpartner_mpesa_till_number_and_more'),
        ('payments', '0011_cashdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayout',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='fleet.fleetpartner'),
        ),
        migrations.AlterField(
            model_name='driverpayout',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='drivers.driver'),
        ),
    ]
