# Generated by Django 6.0.6 on 2026-07-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_driverpayout_organization_alter_driverpayout_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='dispute_resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='dispute_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
