# Generated by Django 6.0.6 on 2026-07-09 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='review_note',
            field=models.CharField(blank=True, help_text='Optional reason, shown to the submitter if rejected.', max_length=255),
        ),
        migrations.AddField(
            model_name='announcement',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending review'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
    ]
