# Generated by Django 6.0.6 on 2026-07-03 21:46

import django.core.validators
import fleet.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='inspection_expiry_date',
            field=models.DateField(blank=True, help_text='NTSA inspection sticker expiry', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_document',
            field=models.FileField(blank=True, help_text='Insurance certificate, max 5MB', null=True, upload_to='fleet/insurance/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), fleet.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
