# Generated by Django 6.0.6 on 2026-07-04 10:24

import django.core.validators
import django.db.models.deletion
import fleet.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_driver_away_reason_driver_is_away_driver_user'),
        ('fleet', '0002_vehicle_inspection_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='drivers.driver'),
        ),
        migrations.CreateModel(
            name='VehicleSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('executive_suv', 'Executive SUV'), ('premium_mpv', 'Premium MPV'), ('compact_sedan', 'Compact Sedan'), ('passenger_van', 'Passenger Van')], max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('passenger_capacity', models.PositiveSmallIntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicle_submissions/', validators=[fleet.validators.validate_file_size])),
                ('logbook_document', models.FileField(help_text='Proof of ownership/registration, max 5MB', upload_to='vehicle_submissions/logbooks/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), fleet.validators.validate_file_size])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_submissions', to='drivers.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
