# Generated by Django 6.0.6 on 2026-07-04 10:42

import django.db.models.deletion
import fleet.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicle_driver_vehiclesubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclesubmission',
            name='photo',
        ),
        migrations.CreateModel(
            name='VehicleSubmissionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_submissions/photos/', validators=[fleet.validators.validate_file_size])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fleet.vehiclesubmission')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
