# Generated by Django 6.0.6 on 2026-07-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_finalize_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to stop offering this type for new vehicles/applications, without deleting it or affecting vehicles that already use it.'),
        ),
    ]
