# Generated by Django 6.0.6 on 2026-07-09 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_finalize_vehicle_category_fk'),
        ('fleet', '0011_vehicle_last_location_at_vehicle_last_location_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('notes', models.CharField(blank=True, help_text='e.g. "Oil change + filter"', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
