# Generated by Django 6.0.6 on 2026-07-10 11:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_vehicleservicerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('mpesa_shortcode', models.CharField(blank=True, help_text="Partner's own Paybill number", max_length=20)),
                ('mpesa_consumer_key', models.CharField(blank=True, max_length=200)),
                ('mpesa_consumer_secret', models.CharField(blank=True, max_length=200)),
                ('mpesa_passkey', models.CharField(blank=True, max_length=200)),
                ('platform_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('10'), help_text="SilverLake's cut of this partner's bookings, owed back by the partner.", max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_company_owned',
            field=models.BooleanField(default=True, help_text='Uncheck if this vehicle is owned by its assigned driver, not by SilverLake - affects whether a with-driver booking on it creates a driver payout.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.fleetpartner'),
        ),
    ]
