# Generated by Django 6.0.6 on 2026-07-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_fleetpartner_mpesa_till_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleetpartner',
            name='mpesa_consumer_key',
        ),
        migrations.RemoveField(
            model_name='fleetpartner',
            name='mpesa_consumer_secret',
        ),
        migrations.RemoveField(
            model_name='fleetpartner',
            name='mpesa_passkey',
        ),
        migrations.RemoveField(
            model_name='fleetpartner',
            name='mpesa_shortcode',
        ),
        migrations.RemoveField(
            model_name='fleetpartner',
            name='mpesa_till_number',
        ),
    ]
