# Generated by Django 6.0.6 on 2026-07-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stafforganization'),
        ('fleet', '0015_remove_fleetpartner_mpesa_consumer_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to='fleet.fleetpartner'),
        ),
    ]
