# Generated by Django 6.0.6 on 2026-07-03 21:46

import bookings.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_id_document',
            field=models.FileField(blank=True, help_text='National ID or passport copy, required for self-drive bookings', null=True, upload_to='bookings/ids/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), bookings.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_license_document',
            field=models.FileField(blank=True, help_text='Required for self-drive bookings', null=True, upload_to='bookings/licenses/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), bookings.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
