# Generated by Django 6.0.6 on 2026-07-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
