# Generated by Django 6.0.6 on 2026-07-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_trip_ended_at_booking_trip_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='driver_token',
        ),
    ]
