# Generated by Django 6.0.6 on 2026-07-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_cancellation_full_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
