# Generated by Django 6.0.6 on 2026-07-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_payment_escalated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ack_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
