# Generated by Django 6.0.6 on 2026-07-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='government_contract_reference',
            field=models.CharField(blank=True, help_text='e.g. department name and LPO/PO number', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_government_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('online', 'Online'), ('driver_onsite', 'Driver (on-site)'), ('admin', 'Staff (Admin)')], default='online', max_length=20),
        ),
    ]
