# Generated by Django 6.0.6 on 2026-07-20 05:47

import bookings.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_booking_discount_code'),
        ('drivers', '0010_driver_cash_payments_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleConditionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('pickup', 'Pickup'), ('return', 'Return')], max_length=10)),
                ('mileage', models.PositiveIntegerField(blank=True, help_text='Odometer reading, km', null=True)),
                ('fuel_level', models.CharField(blank=True, choices=[('empty', 'Empty'), ('quarter', '1/4'), ('half', '1/2'), ('three_quarters', '3/4'), ('full', 'Full')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Existing damage, scratches, anything worth noting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_reports', to='bookings.booking')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drivers.driver')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleConditionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bookings/condition/', validators=[bookings.validators.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bookings.vehicleconditionreport')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vehicleconditionreport',
            constraint=models.UniqueConstraint(fields=('booking', 'report_type'), name='one_report_per_type_per_booking'),
        ),
    ]
