# Generated by Django 6.0.6 on 2026-07-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_vehicleconditionreport_vehicleconditionphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='loyalty_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
