# Generated by Django 6.0.7 on 2026-07-21 15:35

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_booking_loyalty_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(max_length=20, validators=[core.validators.validate_kenyan_phone_number]),
        ),
    ]
