# Generated by Django 6.0.7 on 2026-07-24 08:28

import bookings.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_alter_booking_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_id_document',
            field=models.FileField(blank=True, help_text='National ID or passport copy, required for self-drive bookings', null=True, upload_to='bookings/ids/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), bookings.validators.validate_file_size, bookings.validators.validate_document_content]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_license_document',
            field=models.FileField(blank=True, help_text='Required for self-drive bookings', null=True, upload_to='bookings/licenses/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), bookings.validators.validate_file_size, bookings.validators.validate_document_content]),
        ),
    ]
