# Generated by Django 6.0.7 on 2026-07-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_alter_booking_customer_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_arriving_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
