# Generated by Django 6.0.7 on 2026-07-26 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_booking_driver_arriving_notified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('excess_reduction_description', models.CharField(blank=True, help_text='Customer-facing summary, e.g. "Reduces your excess to KES 20,000".', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order, lowest first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'price_per_day'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='protection_plan_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='protection_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.protectionplan'),
        ),
    ]
