# Generated by Django 6.0.7 on 2026-07-26

from django.db import migrations

# Sensible starting defaults so the protection plan add-on is actually live (not just wired) the
# moment this ships - an admin can freely retune or delete these afterward via the admin
# Protection Plans page (core.views.AdminProtectionPlanViewSet), same as loyalty tiers' own
# seeded defaults (see accounts/migrations/0007_seed_default_loyalty_tiers.py).
DEFAULT_PLANS = [
    ('Basic', 500, 'Reduces your excess to KES 50,000', 0),
    ('Standard', 1000, 'Reduces your excess to KES 20,000', 1),
    ('Premium', 1800, 'Reduces your excess to KES 0', 2),
]


def seed_plans(apps, schema_editor):
    ProtectionPlan = apps.get_model('bookings', 'ProtectionPlan')
    for name, price_per_day, description, order in DEFAULT_PLANS:
        ProtectionPlan.objects.get_or_create(
            name=name,
            defaults={
                'price_per_day': price_per_day,
                'excess_reduction_description': description,
                'order': order,
            },
        )


def unseed_plans(apps, schema_editor):
    ProtectionPlan = apps.get_model('bookings', 'ProtectionPlan')
    ProtectionPlan.objects.filter(name__in=[name for name, *_ in DEFAULT_PLANS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_protectionplan_booking_protection_plan_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_plans, unseed_plans),
    ]
