# Generated by Django 6.0.7 on 2026-07-26 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_seed_default_protection_plans'),
        ('core', '0006_corporateaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='corporate_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.corporateaccount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='corporate_account_reference',
            field=models.CharField(blank=True, help_text='e.g. employee name/department or a PO number', max_length=100),
        ),
    ]
