# Generated by Django 6.0.7 on 2026-07-26

from django.db import migrations

# Government-contract bookings (is_government_contract=True) are being folded into the new,
# registered CorporateAccount concept rather than staying a separate freeform-text field - see
# core.models.CorporateAccount and bookings.models.Booking.bills_via_invoice. This preserves
# every existing booking's own reference text verbatim as a CorporateAccount.name (exact-match
# deduped, since the same LPO/department text sometimes repeats across bookings), rather than
# trying to intelligently group them by department - the freeform text isn't consistent enough
# for that. Migrated accounts start inactive: a one-off historical LPO reference shouldn't
# clutter the picker for new bookings - a department SilverLake actually bills repeatedly should
# be re-registered properly (and reactivated) by a superadmin instead.


def migrate_government_contracts(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    CorporateAccount = apps.get_model('core', 'CorporateAccount')

    for booking in Booking.objects.filter(is_government_contract=True):
        account, _ = CorporateAccount.objects.get_or_create(
            name=booking.government_contract_reference, defaults={'is_active': False},
        )
        booking.corporate_account = account
        booking.save(update_fields=['corporate_account'])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_booking_corporate_account_and_more'),
    ]

    operations = [
        # Not reversible - the following migration drops is_government_contract/
        # government_contract_reference entirely, so there's no way to reconstruct which
        # original boolean/text pair a given CorporateAccount came from once that happens.
        migrations.RunPython(migrate_government_contracts, migrations.RunPython.noop),
    ]
