# Generated by Django 6.0.7 on 2026-07-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_migrate_government_contracts_to_corporate_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='government_contract_reference',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_government_contract',
        ),
    ]
