# Generated by Django 6.0.7 on 2026-07-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0028_booking_dropoff_lat_booking_dropoff_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
