# Generated by Django 6.0.7 on 2026-07-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_booking_pickup_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='review_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
