# Generated by Django 6.0.8 on 2026-09-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_booking_review_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
