# Generated by Django 6.0.6 on 2026-07-11 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0015_remove_fleetpartner_mpesa_consumer_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('driver_acknowledged', 'Driver Acknowledged Booking'), ('booking_created', 'New Booking'), ('booking_cancelled', 'Booking Cancelled'), ('cash_payment_recorded', 'Cash Payment Recorded'), ('payment_disputed', 'Payment Disputed'), ('dispute_resolved', 'Dispute Resolved'), ('driver_away', 'Driver Marked Away'), ('vehicle_submission', 'New Vehicle Submission'), ('driver_application', 'New Driver Application')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('link_path', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='fleet.fleetpartner')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
