# Generated by Django 6.0.6 on 2026-07-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_finalize_vehicle_category_fk'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('driver_acknowledged', 'Driver Acknowledged Booking'), ('booking_created', 'New Booking'), ('booking_cancelled', 'Booking Cancelled'), ('cash_payment_recorded', 'Cash Payment Recorded'), ('payment_disputed', 'Payment Disputed'), ('dispute_resolved', 'Dispute Resolved'), ('driver_away', 'Driver Marked Away'), ('vehicle_submission', 'New Vehicle Submission'), ('driver_application', 'New Driver Application'), ('driver_booked', 'You Were Booked'), ('payment_reminder', 'Payment Reminder'), ('cash_deposit_reminder', 'Cash Deposit Reminder'), ('payout_paid', 'Payout Paid'), ('vehicle_submission_approved', 'Vehicle Submission Approved'), ('vehicle_submission_rejected', 'Vehicle Submission Rejected')], max_length=30),
        ),
    ]
