# Generated by Django 6.0.6 on 2026-07-11 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_driver_alter_notification_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('driver_acknowledged', 'Driver Acknowledged Booking'), ('booking_created', 'New Booking'), ('booking_cancelled', 'Booking Cancelled'), ('cash_payment_recorded', 'Cash Payment Recorded'), ('payment_disputed', 'Payment Disputed'), ('dispute_resolved', 'Dispute Resolved'), ('driver_away', 'Driver Marked Away'), ('vehicle_submission', 'New Vehicle Submission'), ('driver_application', 'New Driver Application'), ('driver_booked', 'You Were Booked'), ('payment_reminder', 'Payment Reminder'), ('cash_deposit_reminder', 'Cash Deposit Reminder'), ('payout_paid', 'Payout Paid'), ('vehicle_submission_approved', 'Vehicle Submission Approved'), ('vehicle_submission_rejected', 'Vehicle Submission Rejected'), ('booking_confirmed', 'Booking Confirmed'), ('trip_completed', 'Trip Completed'), ('payment_recorded', 'Payment Recorded'), ('refund_issued', 'Refund Issued')], max_length=30),
        ),
    ]
