# Generated by Django 6.0.6 on 2026-07-11 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('driver_acknowledged', 'Driver Acknowledged Booking'), ('booking_created', 'New Booking'), ('booking_cancelled', 'Booking Cancelled'), ('cash_payment_recorded', 'Cash Payment Recorded'), ('payment_disputed', 'Payment Disputed'), ('dispute_resolved', 'Dispute Resolved'), ('driver_away', 'Driver Marked Away'), ('vehicle_submission', 'New Vehicle Submission'), ('driver_application', 'New Driver Application'), ('admin_message', 'Message from SilverLake'), ('driver_booked', 'You Were Booked'), ('payment_reminder', 'Payment Reminder'), ('cash_deposit_reminder', 'Cash Deposit Reminder'), ('payout_paid', 'Payout Paid'), ('vehicle_submission_approved', 'Vehicle Submission Approved'), ('vehicle_submission_rejected', 'Vehicle Submission Rejected'), ('booking_confirmed', 'Booking Confirmed'), ('trip_completed', 'Trip Completed'), ('payment_recorded', 'Payment Recorded'), ('refund_issued', 'Refund Issued')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_notification_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'event'), name='unique_user_muted_event')],
            },
        ),
    ]
