# Generated by Django 6.0.6 on 2026-07-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('driver_acknowledged', 'Driver Acknowledged Booking'), ('booking_created', 'New Booking'), ('booking_cancelled', 'Booking Cancelled'), ('cash_payment_recorded', 'Cash Payment Recorded'), ('cash_deposit_logged', 'Cash Deposit Logged'), ('payment_escalated', 'Payment Needs Attention'), ('acknowledgment_overdue', 'Driver Acknowledgment Overdue'), ('payment_disputed', 'Payment Disputed'), ('dispute_resolved', 'Dispute Resolved'), ('driver_away', 'Driver Marked Away'), ('vehicle_submission', 'New Vehicle Submission'), ('driver_application', 'New Driver Application'), ('support_ticket_created', 'New Support Ticket'), ('admin_message', 'Message from SilverLake'), ('driver_booked', 'You Were Booked'), ('payment_reminder', 'Payment Reminder'), ('cash_deposit_reminder', 'Cash Deposit Reminder'), ('payout_paid', 'Payout Paid'), ('vehicle_submission_approved', 'Vehicle Submission Approved'), ('vehicle_submission_rejected', 'Vehicle Submission Rejected'), ('booking_confirmed', 'Booking Confirmed'), ('booking_dates_changed', 'Booking Dates Updated'), ('trip_completed', 'Trip Completed'), ('payment_recorded', 'Payment Recorded'), ('refund_issued', 'Refund Issued'), ('referral_credit_earned', 'Referral Credit Earned'), ('support_ticket_resolved', 'Support Ticket Resolved')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event',
            field=models.CharField(choices=[('driver_acknowledged', 'Driver Acknowledged Booking'), ('booking_created', 'New Booking'), ('booking_cancelled', 'Booking Cancelled'), ('cash_payment_recorded', 'Cash Payment Recorded'), ('cash_deposit_logged', 'Cash Deposit Logged'), ('payment_escalated', 'Payment Needs Attention'), ('acknowledgment_overdue', 'Driver Acknowledgment Overdue'), ('payment_disputed', 'Payment Disputed'), ('dispute_resolved', 'Dispute Resolved'), ('driver_away', 'Driver Marked Away'), ('vehicle_submission', 'New Vehicle Submission'), ('driver_application', 'New Driver Application'), ('support_ticket_created', 'New Support Ticket'), ('admin_message', 'Message from SilverLake'), ('driver_booked', 'You Were Booked'), ('payment_reminder', 'Payment Reminder'), ('cash_deposit_reminder', 'Cash Deposit Reminder'), ('payout_paid', 'Payout Paid'), ('vehicle_submission_approved', 'Vehicle Submission Approved'), ('vehicle_submission_rejected', 'Vehicle Submission Rejected'), ('booking_confirmed', 'Booking Confirmed'), ('booking_dates_changed', 'Booking Dates Updated'), ('trip_completed', 'Trip Completed'), ('payment_recorded', 'Payment Recorded'), ('refund_issued', 'Refund Issued'), ('referral_credit_earned', 'Referral Credit Earned'), ('support_ticket_resolved', 'Support Ticket Resolved')], max_length=30),
        ),
    ]
